name: CI - Build & Push Docker Image

on:
  push:
    branches:
      - stage
      - prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up image tag
        id: vars
        run: |
          SHA=${{ github.sha }}
          BRANCH=${{ github.ref_name }}
          IMAGE_TAG="$BRANCH-${SHA::7}"
          echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          # For stage and prod, use the respective Dockerfile
          docker build -f Dockerfile -t edtechci/edtechfrontend:${{ steps.vars.outputs.tag }} .

      - name: Push Docker image
        run: |
          docker push edtechci/edtechfrontend:${{ steps.vars.outputs.tag }}

      - name: Optionally tag as latest (only for prod)
        if: github.ref_name == 'prod'
        run: |
          docker tag edtechci/edtechfrontend:${{ steps.vars.outputs.tag }} edtechci/edtechfrontend:latest
          docker push edtechci/edtechfrontend:latest
